# Generated by Django 5.2.7 on 2025-10-20 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('entity_id', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('BOARD', 'Board'), ('LIST', 'List'), ('CARD', 'Card')], max_length=10)),
                ('entity_title', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('user_image', models.TextField()),
                ('user_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
            ],
        ),
    ]
